In [43]:
import numpy as np
import pandas as pd
import tensorflow as tf
import nltk

In [44]:
df_true = pd.read_csv("Dataset/True.csv")
df_false = pd.read_csv("Dataset/Fake.csv")

In [45]:
#Add category
df_true["Category"] = 1
df_false["Category"] = 0
print("True News : ", df_true.title.count())
print("False News : ", df_false.title.count())
#Merge into one dataset
df_dataset = pd.concat([df_true, df_false])
print("Dataset : ", df_dataset.title.count())

True News :  21417
False News :  23481
Dataset :  44898


In [46]:
df_dataset["Body"] = df_dataset["title"] + df_dataset["text"]
df_dataset.head()

del df_dataset["text"]
del df_dataset["title"]
del df_dataset["subject"]
del df_dataset["date"]

df_dataset.Body.count()

44898

In [47]:
df_dataset.head()

Category                                               Body
0         1  As U.S. budget fight looms, Republicans flip t...
1         1  U.S. military to accept transgender recruits o...
2         1  Senior U.S. Republican senator: 'Let Mr. Muell...
3         1  FBI Russia probe helped by Australian diplomat...
4         1  Trump wants Postal Service to charge 'much mor...

In [48]:
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS

In [49]:
stopwords = set(stopwords.words('english'))
print(stopwords)

{'he', 'doing', 'ain', 'your', 'shan', 'was', 'you', 'once', 're', 'on', 'such', "won't", 'should', 'by', 'hasn', 'o', "hadn't", 'with', 'aren', 'here', 'himself', 's', 'an', 'so', 'we', 'or', 'doesn', 'had', 'needn', 'theirs', 't', 'both', 'where', "isn't", 'a', 'then', 'after', 'up', 'too', 'these', 'can', 'wasn', 'as', 'being', 'most', 'weren', 'down', 'wouldn', 'been', "haven't", 'other', "you're", "that'll", 'that', "didn't", 'my', 'through', "wasn't", 'don', 'hers', "aren't", 'y', 'i', 'isn', 'him', 'those', 'than', "you've", 'having', 'not', 'same', 'further', "wouldn't", 'about', 'each', 'before', 'them', 'mustn', 'yours', 'll', 'haven', "mightn't", 'which', "you'd", 'off', 've', 'me', 'because', 'd', 'against', 'above', 'hadn', 'all', 'ours', 'ourselves', 'does', 'while', "should've", 'am', 'it', 'of', 'for', 'and', 'when', 'why', 'no', 'itself', 'to', "couldn't", 'there', 'some', 'be', 'nor', 'how', 'just', 'yourselves', "mustn't", 'only', 'now', 'but', 'do', 'over', 'yoursel

In [50]:
df_dataset["Body"]
print(df_dataset["Body"])
df_dataset["Body"].count()

0        As U.S. budget fight looms, Republicans flip t...
1        U.S. military to accept transgender recruits o...
2        Senior U.S. Republican senator: 'Let Mr. Muell...
3        FBI Russia probe helped by Australian diplomat...
4        Trump wants Postal Service to charge 'much mor...
5        White House, Congress prepare for talks on spe...
6        Trump says Russia probe will be fair, but time...
7        Factbox: Trump on Twitter (Dec 29) - Approval ...
8        Trump on Twitter (Dec 28) - Global WarmingThe ...
9        Alabama official to certify Senator-elect Jone...
10       Jones certified U.S. Senate winner despite Moo...
11       New York governor questions the constitutional...
12       Factbox: Trump on Twitter (Dec 28) - Vanity Fa...
13       Trump on Twitter (Dec 27) - Trump, Iraq, Syria...
14       Man says he delivered manure to Mnuchin to pro...
15       Virginia officials postpone lottery drawing to...
16       U.S. lawmakers question businessman at 2016 Tr.

44898

In [51]:
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS
import re


In [56]:
def clean_text(text):
    text = re.sub('\[[^]]*\]', '', text)
    stop = stopwords.words('english')
    text = text.replace('[^\w\s]','')
    final_text = []
    for i in text.split():
#         print(i.strip().lower())
        if i.strip().lower() not in stop:
            final_text.append(i.strip())
    return " ".join(final_text)
    

In [57]:
df_dataset['Body'] = df_dataset['Body'].apply(clean_text)
print(df_dataset["Body"])

0        U.S. budget fight looms, Republicans flip fisc...
1        U.S. military accept transgender recruits Mond...
2        Senior U.S. Republican senator: 'Let Mr. Muell...
3        FBI Russia probe helped Australian diplomat ti...
4        Trump wants Postal Service charge 'much more' ...
5        White House, Congress prepare talks spending, ...
6        Trump says Russia probe fair, timeline unclear...
7        Factbox: Trump Twitter (Dec 29) - Approval rat...
8        Trump Twitter (Dec 28) - Global WarmingThe fol...
9        Alabama official certify Senator-elect Jones t...
10       Jones certified U.S. Senate winner despite Moo...
11       New York governor questions constitutionality ...
12       Factbox: Trump Twitter (Dec 28) - Vanity Fair,...
13       Trump Twitter (Dec 27) - Trump, Iraq, SyriaThe...
14       Man says delivered manure Mnuchin protest new ...
15       Virginia officials postpone lottery drawing de...
16       U.S. lawmakers question businessman 2016 Trump.

In [59]:
from sklearn.model_selection import train_test_split

In [94]:
T = train_test_split(df_dataset.Body, df_dataset.Category, test_size = 0.2,random_state = 0)

In [95]:
print(T)

[16971    TED CRUZ Demands Put Immediate Halt Plans Brin...
1719     Yale Psychiatrists Issue DIRE Warning Dangers ...
2804     Malala Yousafzai’s Message Trump Something EVE...
8837     Sanders expected endorse Clinton Tuesday: New ...
15902    North Korean defector pushes diplomatic soluti...
20055    MOTHER SON KILLED AFGHANISTAN Anti-American 49...
649      Attorney General Sessions says recalls meeting...
10413    WATCH: STONE-FACED ANDERSON COOPER Gets School...
10996    U.S. energy bill caught fight Michigan water c...
13761    Bulgarian, Macedonian Orthodox Churches edge c...
12190    Despite failed round, U.N. Syria talks viable ...
20139    Canadian teens tried use Christmas lights bomb...
10839    U.S. recovers Hellfire air-to-ground missile C...
12783    DONALD TRUMP – VS – CROOKED HILLARY Second Pre...
14385    HERE’S HILLARY CLINTON FORBIDS PRESS Taking Ph...
6631     Watch NRA: President Obama Coming YouWhere Con...
10677    GRANDSTANDING DEM SENATOR SCOLDED Intel Chair 

In [96]:
X_train, X_test, Y_train, Y_test = T

In [97]:
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

16971    TED CRUZ Demands Put Immediate Halt Plans Brin...
1719     Yale Psychiatrists Issue DIRE Warning Dangers ...
2804     Malala Yousafzai’s Message Trump Something EVE...
8837     Sanders expected endorse Clinton Tuesday: New ...
15902    North Korean defector pushes diplomatic soluti...
20055    MOTHER SON KILLED AFGHANISTAN Anti-American 49...
649      Attorney General Sessions says recalls meeting...
10413    WATCH: STONE-FACED ANDERSON COOPER Gets School...
10996    U.S. energy bill caught fight Michigan water c...
13761    Bulgarian, Macedonian Orthodox Churches edge c...
12190    Despite failed round, U.N. Syria talks viable ...
20139    Canadian teens tried use Christmas lights bomb...
10839    U.S. recovers Hellfire air-to-ground missile C...
12783    DONALD TRUMP – VS – CROOKED HILLARY Second Pre...
14385    HERE’S HILLARY CLINTON FORBIDS PRESS Taking Ph...
6631     Watch NRA: President Obama Coming YouWhere Con...
10677    GRANDSTANDING DEM SENATOR SCOLDED Intel Chair .

In [98]:
X_train = np.array(X_train)
Y_train = np.array(Y_train)
X_test = np.array(X_test)
Y_test = np.array(Y_test)

In [99]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(35918,)
(35918,)
(8980,)
(8980,)


In [101]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [108]:
tokenizer = Tokenizer(num_words = 10000, oov_token = "<OOV>")
tokenizer.fit_on_texts(X_train)
word_index = tokenizer.word_index
print(word_index)

{'<OOV>': 1, 'trump': 2, 'said': 3, 'u': 4, 's': 5, 'president': 6, 'would': 7, 'people': 8, '”': 9, 'one': 10, 'state': 11, 'new': 12, 'also': 13, 'reuters': 14, 'house': 15, 'obama': 16, 'clinton': 17, 'donald': 18, 'government': 19, 'states': 20, 'republican': 21, 'year': 22, 'could': 23, 'white': 24, 'united': 25, 'told': 26, 'like': 27, 'campaign': 28, 'two': 29, 'election': 30, 'time': 31, 'news': 32, 'last': 33, 'party': 34, 'first': 35, 'the': 36, 'former': 37, 'hillary': 38, 'even': 39, 'us': 40, 'country': 41, 'years': 42, 'many': 43, 'media': 44, 'it': 45, 'american': 46, 'security': 47, 'law': 48, 'may': 49, 'say': 50, 'police': 51, 'national': 52, 'made': 53, 'political': 54, 'get': 55, 'court': 56, 'right': 57, 'make': 58, 'twitter': 59, 'since': 60, 'republicans': 61, 'going': 62, 'back': 63, 'russia': 64, 'percent': 65, 'according': 66, 'bill': 67, 'presidential': 68, 'says': 69, 'north': 70, 'administration': 71, 'senate': 72, 'support': 73, 'called': 74, 'vote': 75, '

In [117]:
tokenized_train = tokenizer.texts_to_sequences(X_train)
# print(tokenized_train)
padded = pad_sequences(tokenized_train, maxlen = 300, padding = "post")
x_train = padded

In [118]:
print(padded)
print(padded.shape)

[[ 814  296 2042 ...    0    0    0]
 [  25   20  110 ... 3931  482  397]
 [   1    1  550 ...    0    0    0]
 ...
 [7214 7737  588 ...    0    0    0]
 [1379 1354 5356 ...  289 1067  643]
 [3842 2510    1 ...    0    0    0]]
(35918, 300)
