In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import nltk

In [2]:
df_true = pd.read_csv("Dataset/True.csv")
df_false = pd.read_csv("Dataset/Fake.csv")

In [3]:
#Add category
df_true["Category"] = 1
df_false["Category"] = 0
print("True News : ", df_true.title.count())
print("False News : ", df_false.title.count())
#Merge into one dataset
df_dataset = pd.concat([df_true, df_false])
print("Dataset : ", df_dataset.title.count())

True News :  21417
False News :  23481
Dataset :  44898


In [4]:
df_dataset["Body"] = df_dataset["title"] + df_dataset["text"]
df_dataset.head()

del df_dataset["text"]
del df_dataset["title"]
del df_dataset["subject"]
del df_dataset["date"]

df_dataset.Body.count()

44898

In [5]:
df_dataset.head()

Category                                               Body
0         1  As U.S. budget fight looms, Republicans flip t...
1         1  U.S. military to accept transgender recruits o...
2         1  Senior U.S. Republican senator: 'Let Mr. Muell...
3         1  FBI Russia probe helped by Australian diplomat...
4         1  Trump wants Postal Service to charge 'much mor...

In [6]:
from nltk.corpus import stopwords
from wordcloud import WordCloud,STOPWORDS

In [7]:
stopwords = set(stopwords.words('english'))
print(stopwords)

{'is', 'few', 'haven', 'just', 'over', 'the', 'during', 'own', 'shouldn', "should've", 'been', 'how', 'most', 'some', "aren't", 'didn', 'hasn', 'yourself', 'itself', 'there', 'shan', 'wasn', 'our', 'off', 'between', 'if', 'now', 'you', 'nor', 'not', 'so', 'from', 'only', 'doesn', "couldn't", "weren't", 'all', 'ourselves', 'very', 'through', 'wouldn', 'we', 'ma', "you've", 'be', 'too', 'into', 'don', 'once', "isn't", 'than', 'and', "didn't", 'myself', 'those', 'up', "shan't", 'me', 'm', 'to', 'has', 'yours', 'same', 'o', 'll', 'they', 'himself', 'an', 'won', 'having', 'out', 'am', 'her', 'this', "she's", 'theirs', 'what', 't', 'below', "don't", 'until', 'down', 'each', 'them', 'on', 'should', "you'll", 'do', 've', 's', 'did', 'but', 'aren', 'then', 'when', "hasn't", 'no', 'herself', 'as', 'while', 'its', 'will', 'weren', 'above', "doesn't", 'at', 'after', 'd', 'both', 'are', 'of', 'other', 'needn', 'further', 'hadn', "haven't", 'yourselves', 'was', 'about', 'a', 'why', 'who', 'where', '

In [8]:
df_dataset["Body"]
print(df_dataset["Body"])
df_dataset["Body"].count()

0        As U.S. budget fight looms, Republicans flip t...
1        U.S. military to accept transgender recruits o...
2        Senior U.S. Republican senator: 'Let Mr. Muell...
3        FBI Russia probe helped by Australian diplomat...
4        Trump wants Postal Service to charge 'much mor...
5        White House, Congress prepare for talks on spe...
6        Trump says Russia probe will be fair, but time...
7        Factbox: Trump on Twitter (Dec 29) - Approval ...
8        Trump on Twitter (Dec 28) - Global WarmingThe ...
9        Alabama official to certify Senator-elect Jone...
10       Jones certified U.S. Senate winner despite Moo...
11       New York governor questions the constitutional...
12       Factbox: Trump on Twitter (Dec 28) - Vanity Fa...
13       Trump on Twitter (Dec 27) - Trump, Iraq, Syria...
14       Man says he delivered manure to Mnuchin to pro...
15       Virginia officials postpone lottery drawing to...
16       U.S. lawmakers question businessman at 2016 Tr.

44898

In [9]:
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS
import re
import string

In [10]:
def clean_text(text):
    text = text.replace('[^\w\s]','')
    text = text.replace(r"[\"\',]", '')
    text = re.sub('\[[^]]*\]', '', text)
    stop = set(stopwords.words('english'))
    punctuation = list(string.punctuation)
    stop.update(punctuation)
    text = text.replace('[^\w\s]','')
    final_text = []
    for i in text.split():
#         print(i.strip().lower())
        if i.strip().lower() not in stop:
            final_text.append(i.strip())
    return " ".join(final_text)
    

In [11]:
df_dataset['Body'] = df_dataset['Body'].apply(clean_text)
print(df_dataset["Body"][0])

0    U.S. budget fight looms, Republicans flip fisc...
0    Donald Trump Sends Embarrassing New Year’s Eve...
Name: Body, dtype: object


In [12]:
from sklearn.model_selection import train_test_split

In [13]:
T = train_test_split(df_dataset.Body, df_dataset.Category, test_size = 0.2,random_state = 0)

In [14]:
print(T)

[16971    TED CRUZ Demands Put Immediate Halt Plans Brin...
1719     Yale Psychiatrists Issue DIRE Warning Dangers ...
2804     Malala Yousafzai’s Message Trump Something EVE...
8837     Sanders expected endorse Clinton Tuesday: New ...
15902    North Korean defector pushes diplomatic soluti...
20055    MOTHER SON KILLED AFGHANISTAN Anti-American 49...
649      Attorney General Sessions says recalls meeting...
10413    WATCH: STONE-FACED ANDERSON COOPER Gets School...
10996    U.S. energy bill caught fight Michigan water c...
13761    Bulgarian, Macedonian Orthodox Churches edge c...
12190    Despite failed round, U.N. Syria talks viable ...
20139    Canadian teens tried use Christmas lights bomb...
10839    U.S. recovers Hellfire air-to-ground missile C...
12783    DONALD TRUMP – VS – CROOKED HILLARY Second Pre...
14385    HERE’S HILLARY CLINTON FORBIDS PRESS Taking Ph...
6631     Watch NRA: President Obama Coming YouWhere Con...
10677    GRANDSTANDING DEM SENATOR SCOLDED Intel Chair 

In [15]:
X_train, X_test, Y_train, Y_test = T

In [16]:
print(X_train)
print(X_test)
print(Y_train)
print(Y_test)

16971    TED CRUZ Demands Put Immediate Halt Plans Brin...
1719     Yale Psychiatrists Issue DIRE Warning Dangers ...
2804     Malala Yousafzai’s Message Trump Something EVE...
8837     Sanders expected endorse Clinton Tuesday: New ...
15902    North Korean defector pushes diplomatic soluti...
20055    MOTHER SON KILLED AFGHANISTAN Anti-American 49...
649      Attorney General Sessions says recalls meeting...
10413    WATCH: STONE-FACED ANDERSON COOPER Gets School...
10996    U.S. energy bill caught fight Michigan water c...
13761    Bulgarian, Macedonian Orthodox Churches edge c...
12190    Despite failed round, U.N. Syria talks viable ...
20139    Canadian teens tried use Christmas lights bomb...
10839    U.S. recovers Hellfire air-to-ground missile C...
12783    DONALD TRUMP – VS – CROOKED HILLARY Second Pre...
14385    HERE’S HILLARY CLINTON FORBIDS PRESS Taking Ph...
6631     Watch NRA: President Obama Coming YouWhere Con...
10677    GRANDSTANDING DEM SENATOR SCOLDED Intel Chair .

In [17]:
# X_train = np.array(X_train)
# Y_train = np.array(Y_train)
# X_test = np.array(X_test)
# Y_test = np.array(Y_test)

In [18]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(35918,)
(35918,)
(8980,)
(8980,)


In [19]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [20]:
tokenizer = Tokenizer(num_words = 10000)
tokenizer.fit_on_texts(X_train)
word_index = tokenizer.word_index
# print(word_index)

In [21]:
tokenized_train = tokenizer.texts_to_sequences(X_train)
# print(tokenized_train)
padded = pad_sequences(tokenized_train, maxlen = 300, padding = "post")
X_train = padded
tokenized_test = tokenizer.texts_to_sequences(X_test)
X_test = pad_sequences(tokenized_test, maxlen=300)

In [22]:
print(padded)
print(padded.shape)

[[ 813  295 2041 ...    0    0    0]
 [6272  255 6542 ...    0    0    0]
 [ 549    1  234 ...    0    0    0]
 ...
 [7213 7736  587 ...    0    0    0]
 [2127 8245 4193 ...  288 1066  642]
 [3841 2509 6518 ...    0    0    0]]
(35918, 300)


In [38]:
#its important to use the glove.twitter.27B.100d.txt embeddings 
# embedding_dict = {}
# with open("/home/arkasarkar/Desktop/DL_projects/glove.twitter.27B.100d.txt", 'r', encoding = "utf-8") as f:
#     for line in f:
#         values = line.split()
#         word = values[0]
#         vector = np.asarray(values[1:], "float32")
# #         print(word,vector)
#         embedding_dict[word] = vector

def get_coefs(word, *arr): 
    return word, np.asarray(arr, dtype='float32')
embeddings_index = dict(get_coefs(*o.rstrip().rsplit(' ')) for o in open("/home/arkasarkar/Desktop/DL_projects/glove.twitter.27B.100d.txt"))

In [40]:
print((embeddings_index["trump"]))

[-0.24645    0.45248    0.8372     0.1301    -0.10773   -0.23649
 -0.022622  -0.19291    0.0089398 -0.42653    0.46929   -0.2226
 -1.5809    -0.50369    0.302     -0.032982  -0.82088   -0.30826
  0.32375    0.079145   0.45206   -0.60606   -0.021866   0.33313
 -0.023317   0.44279    0.47152   -0.037821  -0.072843  -0.72901
  0.65716    0.19021   -0.34567   -0.71308    0.034026   0.30534
 -0.21855    0.024003  -0.14556   -0.68436    0.93626    0.12909
 -0.17345   -0.68616    0.011613   0.32246   -0.48218   -0.12962
 -0.12519    0.36592   -0.058803  -0.99927   -0.39455    0.29715
 -0.44197    0.16283    0.17432   -0.74203   -0.41865    0.21203
  0.18244   -0.020944   0.051607  -0.17384    0.16151   -0.39944
  0.52242    0.55355   -0.70574    0.1701    -0.22219   -0.61542
 -0.31061   -0.29061    0.10021   -0.058518   0.19118    0.8167
  0.092544   0.25594    0.8109    -0.14547   -0.25681    0.37606
 -0.74676   -0.41652    0.29502   -0.39016   -0.55615   -0.50449
 -0.55999   -0.63991    0.0

In [41]:
max_features = 10000
all_embs = np.stack(embeddings_index.values())
emb_mean,emb_std = all_embs.mean(), all_embs.std()
embed_size = all_embs.shape[1]

word_index = tokenizer.word_index
nb_words = min(max_features, len(word_index))
#change below line if computing normal stats is too slow
embedding_matrix = embedding_matrix = np.random.normal(emb_mean, emb_std, (nb_words, embed_size))
for word, i in word_index.items():
    if i >= max_features: continue
    embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None: embedding_matrix[i] = embedding_vector

/home/arkasarkar/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  


In [42]:
print(embedding_matrix.shape)

(10000, 100)


In [43]:
import math
import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,LSTM,Dropout
from tensorflow.keras.callbacks import ReduceLROnPlateau
import tensorflow as tf

Using TensorFlow backend.


In [44]:
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs = {}):
        if(logs.get('acc') > 0.98):
            print("Accuracy reached 98% stopping training")
            self.model.stop_training = True

def step_decay(epochs):
    initial_lrate = 0.1
    drop = 0.5
    epochs_drop = 10.0
    lrate = initial_lrate * math.pow(drop, math.floor((1+epoch)/epochs_drop))
    return lrate

In [45]:
model = Sequential([
    Embedding(max_features, output_dim = embedding_matrix.shape[1], weights = [embedding_matrix], input_length = 300, trainable = False),
    LSTM(256, return_sequences = True),
    Dropout(0.2),
    LSTM(128, return_sequences = True),
    Dropout(0.2),
    LSTM(64),
    Dropout(0.2),
    Dense(32, activation = 'relu'),
    Dense(1, activation = 'sigmoid')   
    
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr = 0.01, beta_1=0.9, beta_2=0.999, epsilon=1e-07), loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 300, 100)          1000000   
_________________________________________________________________
unified_lstm (UnifiedLSTM)   (None, 300, 256)          365568    
_________________________________________________________________
dropout (Dropout)            (None, 300, 256)          0         
_________________________________________________________________
unified_lstm_1 (UnifiedLSTM) (None, 300, 128)          197120    
_________________________________________________________________
dropout_1 (Dropout)          (None, 300, 128)          0         
_________________________________________________________________
unified_lstm_2 (UnifiedLSTM) (None, 64)                49408     
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0

In [ ]:
history = model.fit(X_train, Y_train, batch_size = 256 , validation_data = (X_test,Y_test) , epochs = 30 , callbacks = [myCallback()])